---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app/version: "APP_VERSION"
  labels:
    app: angular-keycloak
  name: angular-keycloak
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: angular-keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app/version: "APP_VERSION"
  labels:
    app.kubernetes.io/name: angular-keycloak
  name: angular-keycloak
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: angular-keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: angular-keycloak
      namespace: default
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: DOCKER_REGISTRY_HOST/com.mycompany/angular-keycloak:APP_VERSION
          imagePullPolicy: Always
          name: angular-keycloak
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
      imagePullSecrets:
        - name: registry-credentials
